language: c
services: docker
os: linux
env:
    - TARGET=linux64 MODE=Debug
    #Â - TARGET=linux64 MODE=Release
    # - TARGET=windows64
    # - TARGET=android64
script:
    - docker-compose up $TARGET

