sudo: required
dist: trusty
language: c
cache: ccache
services: docker
osx_image: xcode6.4

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release
    - os: osx
      compiler: clang
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

install:
  - pip install --user pyyaml
  - pip install --user poster
  - pip install --user codecov
  - npm install -g npm-check-updates

script:
  - npm-check-updates -u
  - npm install
  - npm test

notifications:
  webhooks: http://artifacts.myftp.biz:3000/api/webhooks
