sudo: required
dist: trusty
language: c
cache: ccache
services: docker

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug COVERAGE=TRUE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

    # Xcode 7.3 (clang)
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3

install:
  - pip install --user pyyaml
  - pip install --user poster
  - pip install --user codecov
  - npm install -g npm-check-updates

script:
  - ncu -u
  - CMAKI_PWD=$(pwd) npm install
  - npm test
  # - npm run upload

deploy:
  provider: npm
  email: "makiolo@gmail.com"
  api_key: "token encrypted with 'travis encrypt YOUR_AUTH_TOKEN --add deploy.api_key'"
  on:
    tags: true

notifications:
  webhooks: http://artifacts.myftp.biz:3000/api/webhooks
