language: cpp

os:
  - linux
  - osx

before_install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; 
    then
        wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
        sudo add-apt-repository --yes "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main";
        sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
        sudo add-apt-repository --yes ppa:h-rayflood/llvm;
        sudo add-apt-repository --yes ppa:andykimpe/cmake;
        sudo apt-get update -qq;
        sudo apt-get install -qq cmake;
        sudo apt-get install -qq $SUPPORT;
        sudo apt-get install -qq $PACKAGE;
    fi

  #setup compiler
  - export CC=${REAL_CC} CXX=${REAL_CXX}

script:
  - mkdir -p $FL_CONF
  - cd $FL_CONF
  - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$FL_CONF -DEXTRA_DEF=$EXTRA_DEF
  - make
  - make test ARGS="-VV"

env:
  - ignore=this

matrix:
  exclude:
    - env: ignore=this
  include:
#clang-3.3
##Debug
    - compiler: clang
      env: REAL_CC=clang-3.3 EXTRA_DEF=-std=c++11 FL_CONF=Debug REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8 
    - compiler: clang
      env: REAL_CC=clang-3.3 EXTRA_DEF=-std=c++1y FL_CONF=Debug REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8 

##Release
    - compiler: clang
      env: REAL_CC=clang-3.3 EXTRA_DEF=-std=c++11 FL_CONF=Release REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8
    - compiler: clang
      env: REAL_CC=clang-3.3 EXTRA_DEF=-std=c++1y FL_CONF=Release REAL_CXX=clang++-3.3 PACKAGE=clang-3.3 SUPPORT=g++-4.8

#clang-3.4
##Debug
    - compiler: clang
      env: REAL_CC=clang-3.4 EXTRA_DEF=-std=c++11 FL_CONF=Debug REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8 
    - compiler: clang
      env: REAL_CC=clang-3.4 EXTRA_DEF=-std=c++1y FL_CONF=Debug REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8 

##Release
    - compiler: clang
      env: REAL_CC=clang-3.4 EXTRA_DEF=-std=c++11 FL_CONF=Release REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8
    - compiler: clang
      env: REAL_CC=clang-3.4 EXTRA_DEF=-std=c++1y FL_CONF=Release REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=g++-4.8

#clang-3.6
##Debug
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++11 FL_CONF=Debug REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9 
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++1y FL_CONF=Debug REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++14 FL_CONF=Debug REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++1z FL_CONF=Debug REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9 

##Release
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++11 FL_CONF=Release REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++1y FL_CONF=Release REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++14 FL_CONF=Release REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9
    - compiler: clang
      env: REAL_CC=clang-3.6 EXTRA_DEF=-std=c++1z FL_CONF=Release REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=g++-4.9

#gcc-4.7
##Debug
    - compiler: gcc
      env: REAL_CC=gcc-4.7   EXTRA_DEF=-std=c++11 FL_CONF=Debug REAL_CXX=g++-4.7     PACKAGE=g++-4.7   SUPPORT=    

##Release
    - compiler: gcc
      env: REAL_CC=gcc-4.7   EXTRA_DEF=-std=c++11 FL_CONF=Release REAL_CXX=g++-4.7     PACKAGE=g++-4.7   SUPPORT=    

#gcc-4.8
##Debug
    - compiler: gcc
      env: REAL_CC=gcc-4.8   EXTRA_DEF=-std=c++11 FL_CONF=Debug REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=    
    - compiler: gcc
      env: REAL_CC=gcc-4.8   EXTRA_DEF=-std=c++1y FL_CONF=Debug REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=    
      
##Release
    - compiler: gcc
      env: REAL_CC=gcc-4.8   EXTRA_DEF=-std=c++11 FL_CONF=Release REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=    
    - compiler: gcc
      env: REAL_CC=gcc-4.8   EXTRA_DEF=-std=c++1y FL_CONF=Release REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT=    
      
#gcc-4.9
##Debug
    - compiler: gcc
      env: REAL_CC=gcc-4.9   EXTRA_DEF=-std=c++11 FL_CONF=Debug REAL_CXX=g++-4.9     PACKAGE=g++-4.9   SUPPORT=
    - compiler: gcc
      env: REAL_CC=gcc-4.9   EXTRA_DEF=-std=c++1y FL_CONF=Debug REAL_CXX=g++-4.9     PACKAGE=g++-4.9   SUPPORT=    
    - compiler: gcc
      env: REAL_CC=gcc-4.9   EXTRA_DEF=-std=c++14 FL_CONF=Debug REAL_CXX=g++-4.9     PACKAGE=g++-4.9   SUPPORT=    
      
##Release
    - compiler: gcc
      env: REAL_CC=gcc-4.9   EXTRA_DEF=-std=c++11 FL_CONF=Release REAL_CXX=g++-4.9 PACKAGE=g++-4.9   SUPPORT=
    - compiler: gcc
      env: REAL_CC=gcc-4.9   EXTRA_DEF=-std=c++1y FL_CONF=Release REAL_CXX=g++-4.9 PACKAGE=g++-4.9   SUPPORT=
    - compiler: gcc
      env: REAL_CC=gcc-4.9   EXTRA_DEF=-std=c++14 FL_CONF=Release REAL_CXX=g++-4.9 PACKAGE=g++-4.9   SUPPORT=

notifications:
  email:
    recipients:
      - makiolo@gmail.com
    on_success: change
    on_failure: always

